apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
  - name: tcp-port
    protocol: TCP
    port: 88
    targetPort: 80
